import { createSiteDataPackage, parseSiteDataPackage } from "./site-data-package.js";

export const NETSCAPE_COOKIE_FILE_MIME_TYPE = "text/plain;charset=utf-8";

const HTTP_ONLY_PREFIX = "#HttpOnly_";
const COOKIE_FILE_HEADER = [
  "# Netscape HTTP Cookie File",
  "# https://curl.se/docs/http-cookies.html",
  "# Generated by Cookie Controller. Do not edit this file while cURL is using it.",
  ""
];

export class NetscapeCookieFileError extends Error {
  constructor(message, { line = 0, code = "INVALID_NETSCAPE_COOKIE_FILE" } = {}) {
    super(line ? `Line ${line}: ${message}` : message);
    this.name = "NetscapeCookieFileError";
    this.code = code;
    this.line = line;
  }
}

export function parseNetscapeCookieFile(input, {
  sourceUrl,
  storeId = "",
  exportedAt = new Date().toISOString()
} = {}) {
  if (typeof input !== "string") {
    throw new NetscapeCookieFileError("Netscape cookie data must be text.");
  }

  const cookies = [];
  const identities = new Set();
  const lines = input.replace(/^\uFEFF/, "").split(/\r?\n/);
  for (const [index, rawLine] of lines.entries()) {
    const lineNumber = index + 1;
    if (!rawLine.trim() || (rawLine.startsWith("#") && !rawLine.startsWith(HTTP_ONLY_PREFIX))) {
      continue;
    }

    const fields = rawLine.split("\t");
    if (fields.length !== 7) {
      throw new NetscapeCookieFileError("Expected 7 tab-separated fields.", { line: lineNumber });
    }

    const [rawDomain, includeSubdomainsValue, path, secureValue, expirationValue, name, value] = fields;
    const httpOnly = rawDomain.startsWith(HTTP_ONLY_PREFIX);
    const domain = normalizeDomain(httpOnly ? rawDomain.slice(HTTP_ONLY_PREFIX.length) : rawDomain, lineNumber);
    const includeSubdomains = parseBooleanField(includeSubdomainsValue, "include-subdomains", lineNumber);
    const secure = parseBooleanField(secureValue, "secure", lineNumber);
    const expirationDate = parseExpiration(expirationValue, lineNumber);
    assertCookieField(path, "Path", lineNumber, { allowEmpty: false });
    if (!path.startsWith("/")) {
      throw new NetscapeCookieFileError("Path must start with /.", { line: lineNumber });
    }
    assertCookieField(name, "Cookie name", lineNumber, { allowEmpty: false });
    assertCookieField(value, "Cookie value", lineNumber, { allowEmpty: true });

    const normalizedDomain = includeSubdomains ? `.${domain}` : domain;
    const identity = JSON.stringify([String(storeId || ""), normalizedDomain, path, name]);
    if (identities.has(identity)) {
      throw new NetscapeCookieFileError(`Duplicate cookie ${name} for ${normalizedDomain}${path}.`, {
        line: lineNumber,
        code: "DUPLICATE_NETSCAPE_COOKIE"
      });
    }
    identities.add(identity);

    cookies.push({
      name,
      value,
      domain: normalizedDomain,
      path,
      secure,
      httpOnly,
      hostOnly: !includeSubdomains,
      storeId: String(storeId || ""),
      session: expirationDate === 0,
      ...(expirationDate === 0 ? {} : { expirationDate })
    });
  }

  if (cookies.length === 0) {
    throw new NetscapeCookieFileError("No Netscape cookie rows were found.", {
      code: "EMPTY_NETSCAPE_COOKIE_FILE"
    });
  }

  return createSiteDataPackage({
    url: sourceUrl,
    exportedAt,
    cookies
  });
}

export function serializeNetscapeCookieFile(dataPackage) {
  const cookies = parseSiteDataPackage(dataPackage).data.cookies;
  if (cookies.length === 0) {
    throw new NetscapeCookieFileError("The selected scope does not contain any cookies.", {
      code: "EMPTY_NETSCAPE_COOKIE_EXPORT"
    });
  }

  const rows = cookies.map((cookie, index) => serializeCookieRow(cookie, index + 1));
  return [...COOKIE_FILE_HEADER, ...rows, ""].join("\n");
}

function serializeCookieRow(cookie, index) {
  const domain = normalizeDomain(cookie.domain, index);
  const includeSubdomains = cookie.hostOnly === false || String(cookie.domain).startsWith(".");
  const domainField = `${cookie.httpOnly ? HTTP_ONLY_PREFIX : ""}${includeSubdomains ? "." : ""}${domain}`;
  const path = cookie.path || "/";
  const expirationDate = cookie.session === true || !Number.isFinite(cookie.expirationDate)
    ? 0
    : Math.trunc(cookie.expirationDate);

  assertCookieField(path, "Path", index, { allowEmpty: false });
  assertCookieField(cookie.name, "Cookie name", index, { allowEmpty: false });
  assertCookieField(cookie.value, "Cookie value", index, { allowEmpty: true });
  if (!path.startsWith("/")) {
    throw new NetscapeCookieFileError("Path must start with /.", { line: index });
  }
  if (!Number.isSafeInteger(expirationDate) || expirationDate < 0) {
    throw new NetscapeCookieFileError("Expiration must be a non-negative integer Unix timestamp.", { line: index });
  }

  return [
    domainField,
    includeSubdomains ? "TRUE" : "FALSE",
    path,
    cookie.secure ? "TRUE" : "FALSE",
    String(expirationDate),
    cookie.name,
    cookie.value
  ].join("\t");
}

function normalizeDomain(value, line) {
  const domain = String(value || "").replace(/^\./, "");
  if (!domain || /[\s/#]/.test(domain)) {
    throw new NetscapeCookieFileError("Cookie domain is invalid.", { line });
  }
  return domain;
}

function parseBooleanField(value, label, line) {
  const normalized = String(value || "").toUpperCase();
  if (normalized !== "TRUE" && normalized !== "FALSE") {
    throw new NetscapeCookieFileError(`${label} must be TRUE or FALSE.`, { line });
  }
  return normalized === "TRUE";
}

function parseExpiration(value, line) {
  if (!/^\d+$/.test(value)) {
    throw new NetscapeCookieFileError("Expiration must be a non-negative integer Unix timestamp.", { line });
  }
  const expirationDate = Number(value);
  if (!Number.isSafeInteger(expirationDate)) {
    throw new NetscapeCookieFileError("Expiration is outside the supported range.", { line });
  }
  return expirationDate;
}

function assertCookieField(value, label, line, { allowEmpty }) {
  if (typeof value !== "string" || (!allowEmpty && !value) || /[\x00-\x1F\x7F]/.test(value)) {
    throw new NetscapeCookieFileError(`${label} cannot be represented in Netscape format.`, { line });
  }
}
